"""empty message

Revision ID: 17732444c237
Revises: abb1a87ac971
Create Date: 2020-04-22 22:53:09.783508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17732444c237'
down_revision = 'abb1a87ac971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'avatar_hash')
    op.drop_column('users', 'location')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('location', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('avatar_hash', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('users', sa.Column('member_since', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('last_seen', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('about_me', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
