"""empty message

Revision ID: a19ea859233c
Revises: 
Create Date: 2020-05-11 23:00:38.255687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19ea859233c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('date_follow', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user_details.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user_details.user_id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
